### ISSUE TITLE
API requests with HTTP code different from 200 not handled correctly

### ISSUE THREAD

**Issue by paglias** [delightedCrow/HabiticaMagic#2]
As reported in https://github.com/delightedCrow/MMM-HabiticaStats/issues/1

> in the HabiticaMagic code here https://github.com/delightedCrow/HabiticaMagic/blob/master/src/HabiticaAPIManager.js#L130 you're resolving the Promise without an error only if the code is 200 but for example the content api often returns a 304 code if the browser (in this case the Electron app) has already cached the last version of the file and nothing has changed. It would be considered as an error even though it's not. I would suggest to use an external library that's been built specifically for making AJAX requests as it's not easy to make it right (for example jQuery.ajax, axios) or the Fetch API which is now available in every browser https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by delightedCrow** [comment]
Thanks for the report!

The reason we don’t currently test for 304 responses is that modern browsers (including the version of chromium bundled with Electron) actually handle this case on a browser level; the browser will receive the 304 response from the server, but behind the scenes it sends our application a 200 response with its cached data as the payload as if the request succeeded as normal. 

You can play with this on our demo here [HabiticaMagicJS - Demo](https://delightedcrow.github.io/HabiticaMagic/docs/demo/demo.html). Notice when you submit a second request, instead of erroring out when the browser gets a 304 for the cached content data,  the browser simply reports the 304 request with a status of 200 (screen shot is an example in the Brave browser, btw):

<img width="1680" alt="Screen Shot 2020-04-08 at 6 24 09 PM" src="https://user-images.githubusercontent.com/480192/78852050-35250b00-79d0-11ea-927e-d0624a78d1b3.png">

Since the [official Habitica API documentation](https://habitica.com/apidoc/#api-Content-ContentGet) doesn’t define any other success codes other than 200, and since we’re currently only supporting modern browsers that already internally handle a 304 request as if it’s a 200, I don’t see the utility in changing the code at this time.

Please feel free to reopen this issue if the Habitica API documentation changes, or you have a specific platform you’d like to support that isn’t working as intended.
